/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Core_IEcoUnknown */

#ifndef _Included_Eco_Core_IEcoUnknown
#define _Included_Eco_Core_IEcoUnknown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Core_IEcoUnknown
 * Method:    QueryInterface
 * Signature: (LEco/Core/UGUID;LEco/Core/IEcoUnknown;)I
 */
JNIEXPORT jint JNICALL Java_Eco_Core_IEcoUnknown_QueryInterface
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     Eco_Core_IEcoUnknown
 * Method:    AddRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_Core_IEcoUnknown_AddRef
  (JNIEnv *, jobject);

/*
 * Class:     Eco_Core_IEcoUnknown
 * Method:    Release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_Core_IEcoUnknown_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
