/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Core_IEcoUnknownNative */

#ifndef _Included_Eco_Core_IEcoUnknownNative
#define _Included_Eco_Core_IEcoUnknownNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Core_IEcoUnknownNative
 * Method:    QueryInterface
 * Signature: (LEco/Core/UGUID;LEco/Core/IEcoUnknownPtr;)S
 */
JNIEXPORT jshort JNICALL Java_Eco_Core_IEcoUnknownNative_QueryInterface
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     Eco_Core_IEcoUnknownNative
 * Method:    AddRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_Core_IEcoUnknownNative_AddRef
  (JNIEnv *, jobject);

/*
 * Class:     Eco_Core_IEcoUnknownNative
 * Method:    Release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_Core_IEcoUnknownNative_Release
  (JNIEnv *, jobject);

/*
 * Class:     Eco_Core_IEcoUnknownNative
 * Method:    GlobalDispatcher
 * Signature: (I[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Eco_Core_IEcoUnknownNative_GlobalDispatcher
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
