/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoFile */

#ifndef _Included_Eco_FileSystemManagement_IEcoFile
#define _Included_Eco_FileSystemManagement_IEcoFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    get_Size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Eco_FileSystemManagement_IEcoFile_get_1Size
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    get_Name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Eco_FileSystemManagement_IEcoFile_get_1Name
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    get_Info
 * Signature: ()LEco/FileSystemManagement/IEcoFileInfo;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFile_get_1Info
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    get_Pointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Eco_FileSystemManagement_IEcoFile_get_1Pointer
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    set_Pointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Eco_FileSystemManagement_IEcoFile_set_1Pointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    Read
 * Signature: (JLjava/lang/Long;)I
 */
JNIEXPORT jint JNICALL Java_Eco_FileSystemManagement_IEcoFile_Read
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    Write
 * Signature: (JLjava/lang/Long;)I
 */
JNIEXPORT jint JNICALL Java_Eco_FileSystemManagement_IEcoFile_Write
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_FileSystemManagement_IEcoFile_Close
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFile
 * Method:    get_Descriptor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Eco_FileSystemManagement_IEcoFile_get_1Descriptor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
