/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_MemoryManager_IEcoMemoryAllocator */

#ifndef _Included_Eco_MemoryManager_IEcoMemoryAllocator
#define _Included_Eco_MemoryManager_IEcoMemoryAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Alloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Alloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Realloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Realloc
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Copy
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Copy
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Fill
 * Signature: (JCJ)J
 */
JNIEXPORT jlong JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Fill
  (JNIEnv *, jobject, jlong, jchar, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    Compare
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_Compare
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryAllocator
 * Method:    RetrieveSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Eco_MemoryManager_IEcoMemoryAllocator_RetrieveSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
