/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Calculator_IEcoCalculatorY */

#ifndef _Included_Eco_Calculator_IEcoCalculatorY
#define _Included_Eco_Calculator_IEcoCalculatorY
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Calculator_IEcoCalculatorY
 * Method:    Multiplication
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Eco_Calculator_IEcoCalculatorY_Multiplication
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Eco_Calculator_IEcoCalculatorY
 * Method:    Division
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Eco_Calculator_IEcoCalculatorY_Division
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
