/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoDirectoryManager */

#ifndef _Included_Eco_FileSystemManagement_IEcoDirectoryManager
#define _Included_Eco_FileSystemManagement_IEcoDirectoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoDirectoryManager
 * Method:    Create
 * Signature: (Ljava/lang/String;)LEco/FileSystemManagement/IEcoDirectoryInfo;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoDirectoryManager_Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Eco_FileSystemManagement_IEcoDirectoryManager
 * Method:    Delete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Eco_FileSystemManagement_IEcoDirectoryManager_Delete
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
