/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_System_CEcoSystem */

#ifndef _Included_Eco_System_CEcoSystem
#define _Included_Eco_System_CEcoSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_System_CEcoSystem
 * Method:    createCEcoSystem
 * Signature: ([Ljava/lang/String;LEco/Core/IEcoSystem1;)S
 */
JNIEXPORT jshort JNICALL Java_Eco_System_CEcoSystem_createCEcoSystem
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     Eco_System_CEcoSystem
 * Method:    deleteCEcoSystem
 * Signature: (LEco/Core/IEcoSystem1;)V
 */
JNIEXPORT void JNICALL Java_Eco_System_CEcoSystem_deleteCEcoSystem
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
