/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_MemoryManager_IEcoMemoryManager */

#ifndef _Included_Eco_MemoryManager_IEcoMemoryManager
#define _Included_Eco_MemoryManager_IEcoMemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_MemoryManager_IEcoMemoryManager
 * Method:    Init
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Eco_MemoryManager_IEcoMemoryManager_Init
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryManager
 * Method:    get_Status
 * Signature: (LEco/MemoryManager/EcoMemoryManagerStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_Eco_MemoryManager_IEcoMemoryManager_get_1Status
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Eco_MemoryManager_IEcoMemoryManager
 * Method:    get_UsedBlocks
 * Signature: ([LEco/MemoryManager/EcoMemoryManagerBlock;[J)Z
 */
JNIEXPORT jboolean JNICALL Java_Eco_MemoryManager_IEcoMemoryManager_get_1UsedBlocks
  (JNIEnv *, jobject, jobjectArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
