/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoFileManager */

#ifndef _Included_Eco_FileSystemManagement_IEcoFileManager
#define _Included_Eco_FileSystemManagement_IEcoFileManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoFileManager
 * Method:    Create
 * Signature: (Ljava/lang/String;)LEco/FileSystemManagement/IEcoFile;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFileManager_Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Eco_FileSystemManagement_IEcoFileManager
 * Method:    Open
 * Signature: (Ljava/lang/String;)LEco/FileSystemManagement/IEcoFile;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFileManager_Open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Eco_FileSystemManagement_IEcoFileManager
 * Method:    Close
 * Signature: (LEco/FileSystemManagement/IEcoFile;)I
 */
JNIEXPORT jint JNICALL Java_Eco_FileSystemManagement_IEcoFileManager_Close
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
