/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoDriveManager */

#ifndef _Included_Eco_FileSystemManagement_IEcoDriveManager
#define _Included_Eco_FileSystemManagement_IEcoDriveManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoDriveManager
 * Method:    get_Drive
 * Signature: (Ljava/lang/String;)LEco/FileSystemManagement/IEcoDriveInfo;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoDriveManager_get_1Drive
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
