/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoDriveInfo */

#ifndef _Included_Eco_FileSystemManagement_IEcoDriveInfo
#define _Included_Eco_FileSystemManagement_IEcoDriveInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoDriveInfo
 * Method:    get_Id
 * Signature: ()LEco/Core/UGUID;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoDriveInfo_get_1Id
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
