/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_InterfaceBus_IEcoInterfaceBus */

#ifndef _Included_Eco_InterfaceBus_IEcoInterfaceBus
#define _Included_Eco_InterfaceBus_IEcoInterfaceBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_InterfaceBus_IEcoInterfaceBus
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eco_InterfaceBus_IEcoInterfaceBus_Init
  (JNIEnv *, jobject);

/*
 * Class:     Eco_InterfaceBus_IEcoInterfaceBus
 * Method:    InitWith
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Eco_InterfaceBus_IEcoInterfaceBus_InitWith
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Eco_InterfaceBus_IEcoInterfaceBus
 * Method:    RegisterComponent
 * Signature: (LEco/Core/UGUID;LEco/Core/IEcoUnknown;)I
 */
JNIEXPORT jint JNICALL Java_Eco_InterfaceBus_IEcoInterfaceBus_RegisterComponent
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     Eco_InterfaceBus_IEcoInterfaceBus
 * Method:    UnRegisterComponent
 * Signature: (LEco/Core/UGUID;)I
 */
JNIEXPORT jint JNICALL Java_Eco_InterfaceBus_IEcoInterfaceBus_UnRegisterComponent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Eco_InterfaceBus_IEcoInterfaceBus
 * Method:    QueryComponent
 * Signature: (LEco/Core/UGUID;LEco/Core/IEcoUnknown;LEco/Core/UGUID;LEco/Core/IEcoUnknown;)I
 */
JNIEXPORT jint JNICALL Java_Eco_InterfaceBus_IEcoInterfaceBus_QueryComponent
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
