/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Core_IEcoSystem */

#ifndef _Included_Eco_Core_IEcoSystem
#define _Included_Eco_Core_IEcoSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Core_IEcoSystem
 * Method:    set_Data
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Eco_Core_IEcoSystem_set_1Data
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Eco_Core_IEcoSystem
 * Method:    get_Data
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Eco_Core_IEcoSystem_get_1Data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
