/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_FileSystemManagement_IEcoFileSystemManagement */

#ifndef _Included_Eco_FileSystemManagement_IEcoFileSystemManagement
#define _Included_Eco_FileSystemManagement_IEcoFileSystemManagement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_FileSystemManagement_IEcoFileSystemManagement
 * Method:    get_FileManager
 * Signature: ()LEco/FileSystemManagement/IEcoFileManager;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFileSystemManagement_get_1FileManager
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFileSystemManagement
 * Method:    get_DirectoryManager
 * Signature: ()LEco/FileSystemManagement/IEcoDirectoryManager;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFileSystemManagement_get_1DirectoryManager
  (JNIEnv *, jobject);

/*
 * Class:     Eco_FileSystemManagement_IEcoFileSystemManagement
 * Method:    get_DriveManager1
 * Signature: ()LEco/FileSystemManagement/IEcoDriveManager;
 */
JNIEXPORT jobject JNICALL Java_Eco_FileSystemManagement_IEcoFileSystemManagement_get_1DriveManager1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
