/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Core_IEcoUnknown_Client */

#ifndef _Included_Eco_Core_IEcoUnknown_Client
#define _Included_Eco_Core_IEcoUnknown_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Core_IEcoUnknown_Client
 * Method:    invokeNative
 * Signature: (I[Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Eco_Core_IEcoUnknown_1Client_invokeNative
  (JNIEnv *, jobject, jint, jobjectArray, jclass);

#ifdef __cplusplus
}
#endif
#endif
