/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eco_Calculator_IEcoCalculatorX */

#ifndef _Included_Eco_Calculator_IEcoCalculatorX
#define _Included_Eco_Calculator_IEcoCalculatorX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eco_Calculator_IEcoCalculatorX
 * Method:    Addition
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Eco_Calculator_IEcoCalculatorX_Addition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Eco_Calculator_IEcoCalculatorX
 * Method:    Subtraction
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Eco_Calculator_IEcoCalculatorX_Subtraction
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
